default_connection_name:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: sfseapac-kr_demo24
      user: ADMIN
      database: PULMUONE_POC
      warehouse: PULMUONE_WH
      schema: PUBLIC
      role: ACCOUNTADMIN
